site_name: "Documentation"
site_url: "https://jason.docs.rokubun.cat"
theme:
  name: material
  logo: 'images/jason_logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'deep orange'
    accent: 'blue grey'
  #custom_dir: 'custom'
  rokubun_url: 'https://jason.rokubun.cat'
nav:
  - 'Description': index.md
  - 'Tutorial': 
    - 'Quick start': quickstart.md
    - 'Manual': manual.md
    - 'Examples': examples.md
    - 'FAQ': faq.md
  - 'Processing strategies' : strategies.md
  - 'Other resources': 'resources.md'
  - 'Contact us': contact.md
extra_css:
  - 'stylesheets/extra.css'
repo_name: 'rokubun/jason-docs'
repo_url: 'https://github.com/rokubun/jason-docs'
extra:
  social:
    - type: 'globe'
      link: 'https://www.rokubun.cat'
    - type: 'twitter'
      link: 'https://twitter.com/rokubn'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/rokubun/'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
google_analytics:
  - 'UA-148380836-1'
  - 'auto'
