site_name: "Documentation"
site_url: "https://jason.docs.rokubun.cat"
theme:
  name: material
  logo: 'images/jason_logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: rokubun
    accent: rokubun-accent
  custom_dir: 'material'
  rokubun_url: 'https://jason.rokubun.cat'
  language: en
  font:
    text: Roboto
    code: Roboto Mononame
  custom_dir: material
  feature:
    tabs: false
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
nav:
  - 'Description': index.md
  - 'GNSS processor': 
    - 'Quick start': quickstart.md
    - 'Manual & API': manual.md
    - 'Examples': examples.md
    - 'Accuracy': accuracy.md
  - 'GNSS converter': converter.md
  - 'Processing strategies' : strategies.md
  - 'Other resources': 'resources.md'
  - 'Contact us': contact.md
extra_css:
  - 'stylesheets/extra.css'
repo_name: 'rokubun/jason-docs'
repo_url: 'https://github.com/rokubun/jason-docs'
extra:
  social:
    - type: 'globe'
      link: 'https://www.rokubun.cat'
    - type: 'twitter'
      link: 'https://twitter.com/rokubn'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/rokubun/'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

google_analytics:
  - 'UA-148380836-1'
  - 'auto'
